apiVersion: v1
kind: ConfigMap
metadata:
  name: buildfolio-config
data:
  PORT: "4000"
  NEXT_PUBLIC_GRAPHQL_URI: "http://backend-service:4000/graphql"
---
apiVersion: v1
kind: Secret
metadata:
  name: buildfolio-secret
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://akarshkbijoy_db_user:oR1kOkGSp8dSxl0q@cluster0.9w39ztw.mongodb.net/csa_class_projects?appName=Cluster0"
  JWT_SECRET: "csa-class-projects-secret-key-2024-super-secure"
